### ISSUE TITLE
Documentation to support feature button presses in apps

### ISSUE THREAD

**Issue by komaxx** [CrosscallEngineering/CoreX5_kernel#1]
Hi @VirfB ,

First of all: I know this is not really an issue of the kernel - but it's quite tough to get in contact with the CrossCall developer team. Sorry, if there's a better way to get in contact that I couldn't find.

I'm working with a Swiss enterprise software development company. One of the company's clients in France is currently equipping their employees with Core-X5 devices. 

Now, they require that the phone's red button launches a specific action in the app I'm developing - regardless of whether the app is currently open or not running at all. Just opening the App is probably not enough (unless there's some Intent extra included?).

Many other handset manufacturers offer special APIs to support use cases like this (Samsung, Spectralink, ..). 
Does CrossCall offer any API to support use cases like this?

**Comment by VirfB** [comment]
Hi Mathias,

I'm pleased to see you have interest in our product.

We have found your request in our ticketing tools and it has been "answered".
Did you receive your answer yet ?

If not, please read the attached document. 
I hope it will help you.

[[B2B][TECH][EN] - Doc - Dedicated Buttons Intents v1.2.pdf](https://github.com/CrosscallEngineering/CoreX5_kernel/files/12082115/B2B.TECH.EN.-.Doc.-.Dedicated.Buttons.Intents.v1.2.pdf)

**Comment by komaxx** [comment]
Hi @VirfB 

thank you for your quick response!
This looks very promising. I'll give it a spin once I receive a CrossCode device to test on :)
